server:
  port: 8078
#  ssl:
#    enabled: true
#    keyAlias: gdoc-batch
#    key-store: /apli/gestordocumental/batch/certificado/gdoc-batch.p12
#    keyStoreType: PKCS12
#    key-store-password: SysFc.DesFc
#    protocol: TLS
#    enabled-protocols: TLSv1.2
debug: false

spring:
  devtools:
    restart:
      enabled: false
#  datasource:
#    url: jdbc:oracle:thin:@172.20.6.16:1521:ODES
#    username: DESARROLLO
#    password: maGn3t0 
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    show-sql: true
#    use_sql_comments: true
#    format_sql: true
#    type: trace
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
